### ISSUE TITLE
anypoint_team_roles crashes if the referenced environment is not yet created / to be created

### ISSUE THREAD

**Issue by drdamour** [mulesoft-anypoint/terraform-provider-anypoint#5]
if i have some hcl like this

```
# https://registry.terraform.io/providers/mulesoft-anypoint/anypoint/latest/docs/resources/env
resource "anypoint_env" "test" {
  org_id   = "x"
  name     = "test"
  type = "production"
}

# https://registry.terraform.io/providers/mulesoft-anypoint/anypoint/latest/docs/resources/team_roles
resource "anypoint_team_roles" "test" {
  org_id  = "x"
  team_id = anypoint_team.devs.id


  roles {
    role_id = "x"
    context_params = {
      org   = "x"
      envId =  anypoint_env.test.id
    }
  }

  roles {
    role_id = "x"
    context_params = {
      org   = "x"
      envId =  "1234"
    }
  }
  

}
```

a terraform plan fails with plugin crash 

```
Stack trace from the terraform-provider-anypoint_v1.5.2.exe plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 131 [running]:
github.com/mulesoft-consulting/terraform-provider-anypoint/anypoint.sortMapListRoles.func1(0x2ede68?, 0xc0007101e0?)
        github.com/mulesoft-consulting/terraform-provider-anypoint/anypoint/resource_team_roles.go:329 +0x574
sort.insertionSort_func({0xc000520970?, 0xc000716c90?}, 0x0, 0x2)
        sort/zsortfunc.go:12 +0xb1
sort.stable_func({0xc000520970?, 0xc000716c90?}, 0x2)
        sort/zsortfunc.go:343 +0x7a
sort.SliceStable({0xb964a0?, 0xc0006890f8?}, 0x2?)
        sort/slice.go:38 +0xe6
github.com/mulesoft-consulting/terraform-provider-anypoint/anypoint.sortMapListRoles({0xc0007101e0, 0x2, 0x2})
        github.com/mulesoft-consulting/terraform-provider-anypoint/anypoint/resource_team_roles.go:315 +0x72
github.com/mulesoft-consulting/terraform-provider-anypoint/anypoint.equalTeamRoles({0xb964a0?, 0xc000689008?}, {0xb964a0?, 0xc0006890c8?})
        github.com/mulesoft-consulting/terraform-provider-anypoint/anypoint/resource_team_roles.go:264 +0xfc
github.com/mulesoft-consulting/terraform-provider-anypoint/anypoint.resourceTeamRoles.func1({0xc000520d00?, 0xc000195800?}, {0xe37060?, 0xc0001949f0?}, {0xcf44d8?, 0x5?}, 0xc0003e3cc0?)
        github.com/mulesoft-consulting/terraform-provider-anypoint/anypoint/resource_team_roles.go:56 +0x1e5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diff(0x6?, {0xe37060, 0xc0001949f0}, {0xcf44d8, 0x5}, 0xc0003e3cc0, 0xc000248a00, {0xe39d10?, 0xc000248a80}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/schema.go:1144 +0x39b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc0003c3a70, {0xe37060, 0xc0001949f0}, 0xc0001f96c0, 0xc0001954d0, 0x0, {0xcd8900, 0xc000108160}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/schema.go:679 +0x353
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0xe37728?, {0xe37060?, 0xc0001949f0?}, 0xc0001f96c0, 0xbee060?, {0xcd8900?, 0xc000108160?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:890 +0x6c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0xc0003b9e60, {0xe37060?, 0xc00025dce0?}, 0xc000623f90)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:741 +0x9c9
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).PlanResourceChange(0xc000207d60, {0xe37060?, 0xc00025c120?}, 0xc0004558f0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:783 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler({0xcbcce0?, 0xc000207d60}, {0xe37060, 0xc00025c120}, 0xc000455880, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:367 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00021c1e0, {0xe3ac58, 0xc0004951e0}, 0xc000681680, 0xc0003f9050, 0x13fb868, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xb2b
google.golang.org/grpc.(*Server).handleStream(0xc00021c1e0, {0xe3ac58, 0xc0004951e0}, 0xc000681680, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-anypoint_v1.5.2.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

of note, if the environment is already present (would need real values set), then the crash does NOT happen since the state file has the value already and the sort works since it casts down to a string. also note if you only have 1 roles block then problem does not happen because sort doesn't seem to be engaged.

Workaround
perform a targeted terraform apply for the environment creation first, then run a full apply for anything referring to that environment (YUCK)

@soufi for attention

**Comment by drdamour** [comment]
also fyi it crashes if the to be determined value is set to org too, so it's either of the values in context_params
```
  roles {
    role_id = "x"
    context_params = {
      org   = anypoint_env.test.id
      envId =  "x"
    }
  }
```

 but it is NOT a problem if you set role_id to it
 ```
   roles {
    role_id = anypoint_env.test.id
    context_params = {
      org   = "x"
      envId =  "x"
    }
  }
 ```
 
 def a bug in https://github.com/mulesoft-anypoint/terraform-provider-anypoint/blob/1a90b4337d7ca126491a9d7c60e897e0da221791/anypoint/resource_team_roles.go#L329 
 
 frankly i don't quite get why context_params exists at all...it should just be
 
 ```
  roles {
    role_id = "roleid"
    org_id   = anypoint_env.test.id
    environment_id =  "env_id"
  }
 ```

**Comment by soufi** [comment]
Hi @drdamour, 
Thanks for reporting this. 
I think there has been some updates on golang or terraform side that made this exact case not working anymore, I had in fact an example that I've been using to test this case that is no longer working. 

Regarding the `context_params` existence, I agree that it's not that relevant, but I stayed as as close as I could to the Mulesoft APIs data-model. As simple as that. and while I'm not close to any member of the API dev crew, it seems more "safe", since you never know what will be the next change ...

To solve this, I'll add a quick check on `org` attribute of the `params_context` in the sort function. should solve the issue. 

I'll push the change to a fix branch, tell me if that solves your issue.

**Comment by soufi** [comment]
new version `v1.5.3` deployed.

**Comment by drdamour** [comment]
got a chance to try this out in 1.5.5 and worked great, thanks!
